name: pipeline

on:
  [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Black check
        run: |
          black . --check --verbose -l 79
      - name: Run isort
        run: |
          isort . --check-only --profile black -l 79
      - name: Run flake8
        run: |
          flake8 . --exclude "*/__init__.py" --ignore "E203,W503"
      - name: Run bandit
        run: |
          bandit -r 'src'
      - name: Run safety
        run: |
          safety check
      - name: Analysing the code with pylint
        run: |
          pylint 'src'